/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BaseRouteLazyImport = createFileRoute('/_base')()
const BaseIndexRouteLazyImport = createFileRoute('/_base/')()

// Create/Update Routes

const BaseRouteLazyRoute = BaseRouteLazyImport.update({
  id: '/_base',
  getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/_base/route.lazy').then((d) => d.Route))

const BaseIndexRouteLazyRoute = BaseIndexRouteLazyImport.update({
  path: '/',
  getParentRoute: () => BaseRouteLazyRoute
} as any).lazy(() => import('./routes/_base/index/route.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BaseRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteLazyImport
      parentRoute: typeof BaseRouteLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BaseRouteLazyRoute: BaseRouteLazyRoute.addChildren({
    BaseIndexRouteLazyRoute
  })
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_base"
      ]
    },
    "/_base": {
      "filePath": "_base/route.lazy.tsx",
      "children": [
        "/_base/"
      ]
    },
    "/_base/": {
      "filePath": "_base/index/route.lazy.tsx",
      "parent": "/_base"
    }
  }
}
ROUTE_MANIFEST_END */
