services:
  postges:
    container_name: taskward-postgres
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    env_file:
      - path: apps/server/.env.local
        required: false
      - path: apps/server/.env
        required: false
