export type CommonTimeFormatter =
  | 'YYYY-MM-DD HH:mm:ss'
  | 'YYYY/MM/DD HH:mm:ss'
  | 'YYYY-MM-DD HH:mm'
  | 'YYYY/MM/DD HH:mm'
  | 'YYYY-MM-DD'
  | 'YYYY/MM/DD'
  | 'MM-DD HH:mm:ss'
  | 'MM/DD HH:mm:ss'
  | 'MM-DD HH:mm'
  | 'MM/DD HH:mm'
  | 'HH:mm:ss'
  | 'HH:mm'

export type LocalTimeFormatter =
  | 'LT'
  | 'LTS'
  | 'L'
  | 'LL'
  | 'LLL'
  | 'LLLL'
  | 'l'
  | 'll'
  | 'lll'
  | 'llll'
